console.log('hi')
console.log('there')
console.log('how')
console.log('are')
console.log('you')
console.log('i')
console.log('am')
console.log('doing')
console.log('fine')
console.log('ugh')
console.log('i')
console.log('am')

console.log('hi')
console.log('there')
console.log('wtf')
console.log('please')
console.log('ugh')
console.log('please')

$('div').each(function() {
  console.log($(this).text())
})
